apiVersion: external-secrets.io/v1beta1
kind: SecretStore.yaml
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-internal.cloudaws.shop:8200/"
      path: "roboshop-dev"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"