name: Terraform apply
on: workflow_dispatch
jobs:
  terraform-apply:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
          url: https://vault-internal.cloudaws.shop:8200
          token: ${{ secrets.VAULT_TOKEN }}
          caCertificate: ${vault_token}
          secrets: |
            github-action/data/azure_sp *;
      env:
        vault_token: ${{ secrets.VAULT_TOKEN }}
      
    - run: make dev-apply vault_token=${vault_token}
      env:
        vault_token: ${{ secrets.VAULT_TOKEN }}