name: Terraform apply
on: workflow_dispatch
jobs:
  terraform-apply:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: make dev-apply vault_token=${vault_token}
      env:
        vault_token: ${{ secrets.VAULT_TOKEN }}
