name: Terraform destroy
on: workflow_dispatch
jobs:
  terraform:
    uses: azawsdevops/github-reusable-modules/.github/workflows/terraform.yaml@main
    with:
      action: destroy
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}